name: Generate snake animation

on:
  schedule: # Execute every 12 hours
    - cron: "0 */12 * * *" 

  workflow_dispatch: # Allow manual execution

  push: # Trigger on changes to the default branch
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write # Permission to push changes
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Generate snake.svg
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      # Step 3: Push snake.svg to the output branch
      - name: Deploy snake.svg to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
